version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/apps/backend"

    schedule:
      interval: "hourly"
    open-pull-requests-limit: 5
    target-branch: "main"
  - package-ecosystem: "npm"
    directory: "/apps/frontend"
    schedule:
      interval: "hourly"
    open-pull-requests-limit: 5
    target-branch: "main"
