version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/apps/backend"
    open-pull-requests-limit: 5
    target-branch: "main"
  - package-ecosystem: "npm"
    directory: "/apps/frontend"
    open-pull-requests-limit: 5
    target-branch: "main"
